### PR TITLE
Fixed custom fields overriding standard fields of the same name

### LINKED ISSUE #9: Stringify custom fields, otherwise data is not sent
When typed fields are mapped with the `hubspot.custom.` prefix, the data is not sent to Hubspot. This is because the integration is not stringifying those values, which it must in order for the query string module to work correctly.

https://github.com/activeprospect/leadconduit-integration-hubspot/blob/860f929504346f5fd81b581bc8951e6514a1d961/src/form.coffee#L46

Associated discussion in Slack: https://activeprospect.slack.com/archives/support/p1429906383000132

### LINKED ISSUE #10: "standard" fields shouldn't be replaceable by "custom" ones
The way this is coded now, the integration replaces "standard" fields with "custom" ones; I don't think it should do that.

For example, if `hubspot.custom.zip` has a mapped value, then the value of `zip` (which is already set from `lead.postal_code`) will be replaced. I would have thought it unusual for users to have such a mapping, but it happened today. :smiley: 

This is related to #9, and a fix for this would have prevented that problem.

### PR DESCRIPTION
**Pull request by jgrayson676**
fix #9 
fix #10

### CODE REVIEW

File: spec/form_spec.coffee [hunk 1]
```diff
@@ -8,6 +8,7 @@ variables = ->
     custom:
       chair: 'Steelcase Leap'
       table: 'Steelcase Floating Table'
+      email: 'foo@bar.com'
```
Comment (cgrayson) [inline spec/form_spec.coffee]: This seems like it would be right, but there's another step to make this test data match what the integration would get with real leads. Take a look at [the setup in the Velocify test](https://github.com/activeprospect/leadconduit-integration-velocify/blob/master/spec/mortgage_spec.coffee#L15). That `buildLeadVars()` helper creates typed objects, so that the email will be an "email" type, instead of a plain string.

Comment (cgrayson) [inline spec/form_spec.coffee]: I think you should be able to invoke that similarly, though separately, under both `custom:` and `lead:`. (I wouldn't be shocked if some existing tests break when you do this; it should have been written this way from the start.)

File: spec/form_spec.coffee [hunk 2]
```diff
@@ -1,38 +1,38 @@
...
-    last_name: 'White'
-    email: 'ww@a1a.com'
-    phone_1: '5127891111'
+    fields.buildLeadVars(lead)
 
 describe 'HubSpot Form Request', ->
   request = null
 
-  beforeEach ->
-    request = integration.request(variables())
```
Comment (cgrayson) [inline spec/form_spec.coffee]: I'd keep this, and the shorter lines in the next 3 tests. 

Then for the more-specific inputs in the last three tests, you could leave them as-is, or use a local variable. Another option would be having a separate `describe()` block, with no `beforeEach()`, for tests on the request body, vs. these on the basic request attributes (`url`, `method`, etc.).

File: spec/form_spec.coffee [hunk 3]
```diff
@@ -1,38 +1,38 @@
...
+    assert.equal integration.request(variables()).method, 'POST'
 
   it 'should have the correct content-type', ->
-    assert.equal request.headers['Content-Type'], 'application/x-www-form-urlencoded'
+    assert.equal integration.request(variables()).headers['Content-Type'], 'application/x-www-form-urlencoded'
 
   it 'should send the correct parameters', ->
-    params = 'email=ww%40a1a.com&firstname=Walter&lastname=White&phone=5127891111&chair=Steelcase%20Leap&table=Steelcase%20Floating%20Table'
-    assert.equal request.body, params
+    assert.equal querystring.parse(integration.request(variables(email: 'foo@bar.com', {})).body).email, 'foo@bar.com'
```
Comment (cgrayson) [inline spec/form_spec.coffee]: I do like this more specific testing better than matching on that whole long `params` string. But now a little test coverage has been lost. I'd keep one or two other, simple fields like `lead.firstname` and `custom.chair`, say.

**Comment by cgrayson** [comment]
LGTM
